#pragma once

#define ARG_USER_NAME				TEXT("user_name")
#define ARG_DOMAIN					TEXT("domain")
#define ARG_PASSWORD				TEXT("password")
#define ARG_WORKING_DIRECTORY		TEXT("working_directory")
#define ARG_EXIT_CODE_BASE			TEXT("exit_code_base")
#define ARG_ENV_VAR					TEXT("environment_var")
#define ARG_CONFIGURATION_FILE		TEXT("configuration_file")
#define ARG_EXECUTABLE				TEXT("executable")
#define ARG_EXIT_COMMAND_LINE_ARGS	TEXT("command_line_args")
#define ARG_INHERITANCE_MODE		TEXT("inheritance_mode")
#define ARG_LOG_LEVEL				TEXT("log_level")
#define ARG_INTEGRITY_LEVEL			TEXT("integrity_level")
#define ARG_SHOW_MODE				TEXT("show_mode")
#define ARG_SELF_TESTING			TEXT("self_testing")
